# dbus-mqtt-switch — config-light5.ini
# Switch 5 — RGBW light (type 13)

[DEFAULT]
logging         = WARNING
device_name     = Switch 5
device_instance = 204
timeout         = 120
type            = 13

[MQTT]
broker_address  = 127.0.0.1
broker_port     = 1883
topic           = triaca/switch/light5
