# dbus-mqtt-switch — Switch 3 (RGB LED)
# ======================================
# ESP32-C6 WS2812 RGB LED → Venus OS type 11 (RGB)

[DEFAULT]
logging = WARNING
device_name = Switch 3
device_instance = 202
timeout = 120
type = 11

[MQTT]
broker_address = 127.0.0.1
broker_port    = 1883
topic          = triaca/switch/light3
