# dbus-mqtt-switch — config-light4.ini
# Switch 4 — CCT light (type 12)

[DEFAULT]
logging         = WARNING
device_name     = Switch 4
device_instance = 203
timeout         = 120
type            = 12

[MQTT]
broker_address  = 127.0.0.1
broker_port     = 1883
topic           = triaca/switch/light4
